### ISSUE TITLE
Support Dark Theme in JBTheme

### ISSUE THREAD

**Issue by DevSrSouza** [ButterCam/compose-jetbrains-theme#10]
Would be awesome to see maybe IntelliJ Dracula Theme as Dark Theme

**Comment by DevSrSouza** [comment]
https://github.com/ButterCam/compose-jetbrains-theme/pull/12

**Comment by devkanro** [comment]
@DevSrSouza 

Sorry for replying so late, I am missing notifacation

**Comment by devkanro** [comment]
I will take some test before releasing 1.1.0, thanks for your contribution.

**Comment by devkanro** [comment]
It looks awesome, thanks.

<img width="912" alt="截屏2022-07-19 下午8 26 02" src="https://user-images.githubusercontent.com/9367842/179759405-50723fea-5f75-404a-a832-79cb987e6cb8.png">
.
