### ISSUE TITLE
Allow passing in `undecorated` and `transparent` arguments to `JBWindow` function

### ISSUE THREAD

**Issue by Olivki** [ButterCam/compose-jetbrains-theme#18]
Currently the `undecorated` and `transparent` arguments of the `Window` function are hard-coded to be set to `false`, it would be nice if instead the `JBWindow` function would allow one to define the `undecorated` and `transparent` arguments.

Having `undecorated` and `transparent` set to `true` does not seem to cause any issues, at least on Windows, from my testing.

Along with this, it would be nice if some way of wrapping the `MainToolBar` in a `DraggableWindowArea` was provided, most likely a separate `JBWindow` function would be the best solution. This would allow one to have a custom tool bar with drag functionality without needing to use the JetBrains Runtime, which might not be possible to use in a project.

It *is* possible to achieve this with the current functions provided, but it would essentially result in a re-implementation of the entire `JBWindow` system, which feels like a waste of time and resources when the system is already implemented and would only require some small tweaks to allow the desired functionality.

**Comment by devkanro** [comment]
JBWindow is designed for JetBrains Runtime only, but I still think it is a good idea to abstract the MainToolBar so that developers can customize the undecorated style of the window.

But using undecorated windows has disadvantages that cannot be ignored.

For example, you need to draw your own window shadows, which are difficult to standardize across systems. Linux provides shadows for undecorated windows, while Windows and macOS do not.

In fact, I tried to use undecorated windows on Linux to implement JBWindow, but a series of defects such as the inability to provide rounded borders made me give up on this solution.

In addition, WindowDraggableArea has a drawback that cannot be ignored. It does not yet support more gestures, such as double-clicking to maximize, dragging to the edge of the screen to split the display, and so on.

**Comment by devkanro** [comment]
There is no additional cost to use Compose Desktop with JBR for distribution, all that is required is that your development and compilation environments have JBR, not that the end machine.

If you package your application using the package task of the Compose Desktop Gradle plugin in a JBR environment, the distribution will also come with its own JBR environment. It will also work fine when installed on a machine that does not contain a JBR environment.

**Comment by Olivki** [comment]
> In addition, WindowDraggableArea has a drawback that cannot be ignored. It does not yet support more gestures, such as double-clicking to maximize, dragging to the edge of the screen to split the display, and so on.

I hadn't considered the loss of the gesture support, while the double-clicking to maximize could be implemented, the dragging to edge is a completely different rabbit hole.

But like you said, abstracting the `MainToolBar` is probably a good middle ground, as the user can they decide what they want to do without having the re-implement all of `MainToolBar`.

---

> There is no additional cost to use Compose Desktop with JBR for distribution, all that is required is that your development and compilation environments have JBR, not that the end machine.

My concern with using JBR wasn't with the end-user not having it, bundling works as it should. For my specific use case using JBR is problematic as, from what I can see, JBR is only provided for the JDK "LTS" versions, that being JDK 11 and JDK 17. I personally need to use the new [Foreign Function & Memory API](https://openjdk.org/jeps/424) that was introduced in JDK 19, so JBR is not usable for me.

**Comment by devkanro** [comment]
OK, I will create new release in this weekend for it.

**Comment by devkanro** [comment]
In d8727630aa673010579fe6c28512913f3d9764b3, provide a control named `BasicMainToolBar`, you can use it simply

```Kotlin
BasicMainToolBar {
    // Your content
}
```

**Comment by devkanro** [comment]
Fixed in [2.1.0](https://github.com/ButterCam/compose-jetbrains-theme/releases/tag/v2.1.0)
