### ISSUE TITLE
`WindowState.placement` action button in `MainToolBar` still shown when `resizable` is `false`

### ISSUE THREAD

**Issue by Olivki** [ButterCam/compose-jetbrains-theme#19]
When `resizable` in `JBWindow` is `false` I expected the minimize/maximize button to be hidden, as minimizing/maximizing a window is a resizing operation. Currently that button is still there even if `resizable` is `false`.

Hiding the minimize/maximize if a window isn't resizable is at least the default behavior on Windows, unsure about other systems.

Only tested on Windows 10.

**Comment by devkanro** [comment]
I will check it later

**Comment by devkanro** [comment]
It has been fixed in d8727630aa673010579fe6c28512913f3d9764b3

Can you help me to test it in Windows?

**Comment by devkanro** [comment]
Fixed in [2.1.0](https://github.com/ButterCam/compose-jetbrains-theme/releases/tag/v2.1.0)
