### ISSUE TITLE
Toolbar in new UI is not applying JBR patches when it has no children

### ISSUE THREAD

**Issue by rock3r** [ButterCam/compose-jetbrains-theme#20]
In the new UI sample, on JBR, if you remove the title and content from the main toolbar, it renders incorrectly (below the system chrome instead of replacing it):

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/153802/205073751-89565fe7-ed43-4c93-8076-d122d09eee6a.png">

It should render the custom title bar correctly even when it has no title and no content

**Comment by devkanro** [comment]
It has been fixed in d8727630aa673010579fe6c28512913f3d9764b3

**Comment by devkanro** [comment]
Fixed in [2.1.0](https://github.com/ButterCam/compose-jetbrains-theme/releases/tag/v2.1.0)
