### ISSUE TITLE
 A system toolbar appears on Windows when building through a runDistributable

### ISSUE THREAD

**Issue by MaxLuxs** [ButterCam/compose-jetbrains-theme#24]
Good afternoon.
While using the library, I discovered a problem on windows.
When I compile the project to a normal run task then everything works as expected. But when I run distributable, the Windows system toolbar appears above the jetbrains toolbar. Is there such a defect? Or am I doing something wrong?

![Снимок экрана 2023-08-10 205915](https://github.com/ButterCam/compose-jetbrains-theme/assets/93794254/c1d05d49-b037-46dd-a189-23f7d744a931)

![Снимок экрана 2023-08-10 210003](https://github.com/ButterCam/compose-jetbrains-theme/assets/93794254/50dabbc4-83c5-4061-8f6e-3a025fe3f4be)

Code: 
```kotlin
JBWindow(
        onCloseRequest = {
            viewModel.stopWork()
            exitApplication()
        },
        title = "Asins Filter",
        state = windowState,
        theme = theme,
        mainToolBar = {
            Row(Modifier.mainToolBarItem(Alignment.End)) {
                    ActionButton(
                        { isDark = !isDark }, Modifier.size(32.dp), shape = RectangleShape
                    ) {
                        if (isDark) {
                            Icon("darkTheme.svg")
                        } else {
                            Icon("lightTheme.svg")
                        }
                    }
            }
        }
    ) {
```

**Comment by devkanro** [comment]
Are you sure you build distributable with JBR-17?

**Comment by devkanro** [comment]
Plz check the readme
https://github.com/ButterCam/compose-jetbrains-theme#jetbrains-runtime

**Comment by MaxLuxs** [comment]
Thanks for the help. Installing jbr in JAVA_HOME helped
